Repository systopia/de.systopia.remotetools, pull requests merged in 2024-03, with the labels that each got.

#24 ContactRoles: Prevent iteration over string
  CRM/Remotetools/ContactRoles.php
Labels: bug, status:needs review

#29 Do not try to `explode()` return parameter when it already is an array
  Civi/RemoteToolsRequest.php
Labels: bug, status:reviewed and tested

#32 Add support for tagged data (`$tag`) in JSON schema
  Civi/RemoteTools/JsonSchema/Validation/ValidationResult.php
  Civi/RemoteTools/JsonSchema/Validation/Validator.php
  composer.json
Labels: feature, status:needs review
